name: Pull Request
on:
    pull_request:
jobs:
    checkPR:
        runs-on: ubuntu-latest
        steps:
            -   name: Check PR
                uses: deltastone/build-and-release@v2.0.0
                with:
                    mode: 'PR'
                    token: ${{ secrets.PAT }}
